language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
script:
  - coveralls/make --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
before_install:
  - pip install coveralls
after_success:
  - coveralls
