language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
script:
  - make
before_install:
  - pip install coveralls
after_success:
  - coveralls
